RDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY:
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-ord.fullname" . }}--ord
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  FABRIC_LOGGING_SPEC: "DEBUG"
  ORDERER_GENERAL_ORDERERTYPE: {{ .Values.ord.type | quote }}
  ORDERER_GENERAL_LISTENADDRESS: "0.0.0.0"
  ORDERER_HOST: {{ .Values.ingress.hosts | quote }}
  ORDERER_GENERAL_BOOTSTRAPMETHOD: "file"
  ORDERER_GENERAL_BOOTSTRAPFILE: "/var/hyperledger/orderer/genesis/genesis.block"
  ORDERER_GENERAL_LISTENPORT: "7050"
  # ORDERER_GENERAL_GENESISMETHOD: "file"
  # ORDERER_GENERAL_GENESISFILE: /var/hyperledger/orderer/genesis/genesis.block
  ORDERER_GENERAL_LOCALMSPID: {{ .Values.ord.mspID | quote }}
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
  #enabled TLS
  ORDERER_GENERAL_TLS_ENABLED: {{ .Values.ord.tls.server.enabled | quote }}
  ORDERER_GENERAL_TLS_PRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_TLS_CERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR: "1"
  ORDERER_KAFKA_VERBOSE: "true"
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_GENERAL_LOGLEVEL: "debug"
  ORDERER_OPERATIONS_LISTENADDRESS: "0.0.0.0:9443"
  ORDERER_METRICS_PROVIDER: prometheus
  #ORDERER_GENERAL_CLUSTER_ROOTCAS: {{ .Values.ord.tls.server.paths | quote }}
  #ADMIN_MSP_PATH: /var/hyperledger/admin_msp