apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certs-rotation-binding
  namespace: certs-rotation
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certs-rotation-role # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: certs-rotation-sa # service account to bind to
  namespace: certs-rotation  # ns of service account