apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-rotation-volume
  namespace: certs-rotation
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/certs-rotation"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-rotation-claim
  namespace: certs-rotation
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
