apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-ca.fullname" . }}--ca
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  GODEBUG: "netdns=go"
  #FABRIC_CA_HOME: /var/hyperledger/fabric-ca
  FABRIC_CA_SERVER_CA_NAME: {{ .Values.caName | quote }}
  SERVICE_DNS: 0.0.0.0  # Point to itself
  FABRIC_CA_HOME: /etc/hyperledger/fabric-ca
  FABRIC_CA_SERVER_CA_NAME: {{ .Values.config.csr.names.ou | quote }}
  FABRIC_CA_SERVER_CSR_C: {{ .Values.config.csr.names.c | quote }}
  FABRIC_CA_SERVER_CSR_ST: {{ .Values.config.csr.names.st | quote }}
  FABRIC_CA_SERVER_CSR_L: {{ .Values.config.csr.names.l | quote }}
  FABRIC_CA_SERVER_CSR_O: {{ .Values.config.csr.names.o | quote }}
  FABRIC_CA_SERVER_CSR_CN: {{ .Values.config.csr.names.ou | quote }}
  FABIRC_CA_SERVER_DEBUG: "true"
  FABRIC_CA_SERVER_PORT: "7054"
  FABRIC_CA_SERVER_TLS_ENABLED: "true"
  FABRIC_CA_SERVER_CSR_HOSTS: 0.0.0.0,{{ .Values.config.csr.names.ou }}
  FABRIC_CA_SERVER_CA_KEYFILE: /etc/hyperledger/fabric-ca/{{ .Values.config.csr.names.ou }}-key.pem
  FABRIC_CA_SERVER_CA_CERTFILE: /etc/hyperledger/fabric-ca/{{ .Values.config.csr.names.ou }}-cert.pem
