{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hlf-peer.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "labels.standard" . | indent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
##{{- if .Values.ingress.tls }}
#  tls:
#  {{- range .Values.ingress.tls }}
#    - hosts:
#      {{- range .hosts }}
#        - {{ . }}
#      {{- end }}
#      secretName: {{ .secretName }}
#  {{- end }}
##{{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: request
        # paths:
        #   #- path: {{ $ingressPath }}
        # - backend:
        #     serviceName: {{ $fullName }}
        #     servicePort: request
  {{- end }}
{{- end }}
