apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      nodePort: {{ .Values.service.NodePort }}
      protocol: TCP
      name: request
  #  - port: {{ .Values.service.portEvent }}
  #    targetPort: 7053
  #    protocol: TCP
  #    name: event
    - port: 7052
      targetPort: 7052
      protocol: TCP
      name: chaincode
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: operations
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
